enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[GPhotos]
app-name = "GPhotos-CR"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
arch = "arm64-v8a"
version = "auto"
included-patches = "'Enable DCIM folders backup control'"

[Recorder]
app-name = "Recorder-CR"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/google-recorder/"
arch = "arm64-v8a"
apkmirror-dpi = "nodpi"
version = "4.2.20241220.725581069"

[Facebook]
app-name = "Facebook-CR"
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/facebook/"
arch = "arm64-v8a"

